# Site setings
name: 'The Black Texan'
description: 'All things Black. All things Texan.'
# Sidebar about text
site_description: 'All things Black. All things Texan. The Black Texan is a site devoted to chronicling and uplifting the black experience in Texas.'
logo: 'assets/images/logo/website-logo.svg'
favicon: 'assets/images/favicon/faicon.ico'
baseurl:
production_url: https://blacktexan.com/
disqus: 'the-black-texan'
mailchimp_url: False
# Add your GA Tracking Id
ga_analytics: 'UA-168796866-1'

# Contact form setings
email: contact@blacktexan.com
contact_page_description: False
thankyou_page_description: "Your message has been successfully sent. We will contact you very soon!"

# Social links
twitter: 'TexanBlack'
facebook: False
github: False
codepen: False
dribbble: False
medium: False
instagram: False
pinterest: False
linkedin: False

# Navigation
navigation:
  - text: About
    url: /about
  - text: Articles
    url: /#main
  - text: Reviews
    url: /tag/review
  - text: Contact
    url: /contact

# Required Plugins
plugins_dir:
  - jekyll-paginate
  - jekyll-tagsgenerator
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-author-page

# Pagination
paginate: 6
paginate_path: /page:num/

# Permalinks
permalink: /:title

# Other
markdown: kramdown

# Sass
sass:
  sass_dir: _sass
  style: compressed
  
tags:
- jekyll
- pagination

plugins:
  - jekyll-sitemap
